# 向 PV請求，空間
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asiayo-pvc
  namespace: asiayo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
