# 儲存 MySQL的PASSWORD和DATABASE
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: asiayo
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YXNpYXlv # "asiayo" 的 Base64 編碼
  MYSQL_DATABASE: YXNpYXlv          # "asiayo" 的 Base64 編碼
